### ISSUE TITLE
Reinstalling app

### ISSUE THREAD

**Issue by ioRekz** [oren/docker-cordova#1]
Hello, 
Are you able to rerun an already installed app ?
I have to uninstall it on the device otherwise I have a certificate failure

**Comment by oren** [comment]
I believe I have to uninstall it only once. I will try it tomorrow and update here.

**Comment by oren** [comment]
i think it might be an expected behavior of android.
You can delete the app from the device:
```
docker run --rm -i -v $(pwd):/workspace -w /workspace --privileged -v /dev/bus/usb:/dev/bus/usb cordova adb devices <bundle id>
```

let me know!
