### ISSUE TITLE
certificate not trusted

### ISSUE THREAD

**Issue by ndealmeida** [oren/docker-cordova#10]
Hello,
I can run ```cordova create hello```, ```cd hello```, but I can't run ```cordova platform add android```. I get "Unable to fetch platform android: Error: certificate not trusted". Can you help me? Thank you!

**Comment by sebastienheyd** [comment]
I have the same error on Ubuntu 18.04

**Comment by AwdotiaRomanowna** [comment]
Setting NODE_TLS_REJECT_UNAUTHORIZED=0 helped in my case

**Comment by phil294** [comment]
which then again, results in `Unable to fetch platform android: Error: SSL Error: CERT_UNTRUSTED`. This can be solved by adding `RUN npm config set strict-ssl false` to the Dockerfile (and rebuilding). Only to fail again at
```
Unzipping /src/gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b/gradle-2.2.1-all.zip to /src/gradle/wrapper/dists/gradle-2.2.1-all/2m8005s69iu8v0oiejfej094b
Exception in thread "main" java.lang.RuntimeException: java.util.zip.ZipException: zip file is empty
```
so it seems this repository is pretty much unusable today. not really sure what the underlying issue is

**Comment by hicksjduk** [comment]
I have experienced the same error today. I love the idea behind this repo, but need some help to get it working please.

**Comment by bradjones1** [comment]
Unfortunately I don't work with Cordova any longer and I don't think there is much work in general in this space by other contributors.

**Comment by hicksjduk** [comment]
Thanks. I've given up on Cordova as it's too hard to make it work.

**Comment by ghost** [comment]
Had the same problem. To solve it i first went into a shell in the container
`docker run -it  -v $PWD:/src cordova bash`

from within i run:
```
npm config set registry http://registry.npmjs.org/
npm config set strict-ssl false
cordova platform add android
```

(which is a non recomended answer from https://stackoverflow.com/questions/13913941/how-to-fix-ssl-certificate-error-when-running-npm-on-windows)

But later doing `cordova build` i got a 403 FORBIDDEN from http://services.gradle.org/distributions/gradle-2.2.1-all.zip which i could verify it was not working doing `wget http://services.gradle.org/distributions/gradle-2.2.1-all.zip`

There is definetly something broken with the SSL client libs in the container.

I could solve this by changing the URL to HTTPS, by executing the command:
`sed -i 's/distributionUrl=http/distributionUrl=https/' platforms/android/cordova/lib/build.js`

And voila, *BUILD SUCCESSFUL*

**Comment by ndealmeida** [comment]
I don't use the tool anymore, closing it.
