### ISSUE TITLE
Block on Step 7

### ISSUE THREAD

**Issue by Yoann-TYT** [oren/docker-cordova#3]
Hi,

It block on step 7 

Step 7 : RUN ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | /usr/local/android-sdk-linux/tools/android update sdk --no-ui -a --filter platform-tool,build-tools-22.0.1,android-22;     find /usr/local/android-sdk-linux -perm 0744 | xargs chmod 755

I'm on macbook pro. - OS X Yosemite and docker is correctly installed

Thanks for your help ;)

**Comment by ascheman** [comment]
Sure? Works for me ;-)

It downloads a lot of stuff, so maybe if your internet connection is slow it may appear as if it blocks ...

However, you may run the commands manually and will see some progress then.

1. Just start docker: ```docker run -rm -ti kallikrein/cordova:5.1.1```
2. Then run the following command step by step

```
apt-get update && apt-get install -y lib32stdc++6 lib32z1
curl http://dl.google.com/android/android-sdk_r24.2-linux.tgz | tar xz -C /usr/local/
export ANDROID_HOME /usr/local/android-sdk-linux
export ANDROID_HOME=/usr/local/android-sdk-linux
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
/usr/local/android-sdk-linux/tools/android update sdk --no-ui -a --filter platform-tool,build-tools-22.0.1,android-22
find /usr/local/android-sdk-linux -perm 0744 | xargs chmod 755
```

During the android SDK update you may be asked several times to confirm license agreements etc. by typing 'y'. Then you should see a lot of download information, e.g.,

```
Installing Archives:
  Preparing to install archives
  Downloading Android SDK Platform-tools, revision 23.0.1
  Installing Android SDK Platform-tools, revision 23.0.1
  Stopping ADB server failed (code -1).
    Installed Android SDK Platform-tools, revision 23.0.199%)
  Downloading Android SDK Platform-tools, revision 23.1 rc1
  Installing Android SDK Platform-tools, revision 23.1 rc1
    Stopping ADB server succeeded.
    Installed Android SDK Platform-tools, revision 23.1 rc199%)
  Downloading Android SDK Build-tools, revision 22.0.1
  Installing Android SDK Build-tools, revision 22.0.1
    Installed Android SDK Build-tools, revision 22.0.199%)
  Downloading SDK Platform Android 5.1.1, API 22, revision 2
  Installing SDK Platform Android 5.1.1, API 22, revision 2
    Installed SDK Platform Android 5.1.1, API 22, revision 296%)
    Stopping ADB server succeeded.
    Starting ADB server succeeded.
  Done. 4 packages installed.
```

If anything goes wrong, please post an error message or what happened here.

**Comment by Yoann-TYT** [comment]
Thanks for your fast response ;)

I test it manually, and the result is the same... I have got no response, no error. It's a problem with my MacBook because on my old Asus with Linux Mint OS, It works successfully... 

So, I'm sad :( ...

**Comment by oren** [comment]
any updates on this issue?
