### ISSUE TITLE
Can't detect device LG G4

### ISSUE THREAD

**Issue by vasspilka** [oren/docker-cordova#4]
Can't detect device, USB debugging enabled, any help?

![screenshot_20160120_213752](https://cloud.githubusercontent.com/assets/3274419/12460773/147566aa-bfbe-11e5-9350-7f2dbfd14af8.png)

**Comment by oren** [comment]
the issue might be the cable, the usb port, your phone's model and version or even your operating system. try replacing those and see if it helps.

**Comment by vasspilka** [comment]
Hello sorry this is now old, can't remember if I got it working or not. Should I close this?
