### ISSUE TITLE
Ionic ?

### ISSUE THREAD

**Issue by sylvainar** [oren/docker-cordova#6]
Hey !

Is it possible to add Ionic in the container, or at least an option during the install to chose if we want ionic or not ? It could be really useful !

Anyway, thank you so much for this, I really needed that kind of automation! If only I found this before, could have easily saved 3+ hours installation. Nice work !

**Comment by oren** [comment]
That's a great idea. I added you as a collaborator so if you feel like doing it, go ahead!

**Comment by bradjones1** [comment]
@oren @sylvainar FWIW I have refactored this project a bit in my fork at https://github.com/bradjones1/docker-cordova which includes Ionic, among some version bumps and removing the dependency on Oren's other repos. Let me know if you think any of it belongs here.

**Comment by oren** [comment]
if you want to, go ahead and modify this one. It's up to you. Thanks!
